# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src/FEO.CMS.HBG.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
    feedsToUse: config
    nugetConfigPath: 'src/FEO.CMS.HBG/nuget.config'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=false /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Create packed NuGet files Corporate'
  inputs:
    command: 'pack'
    packagesToPack: 'src/FEO.CMS.HBG/FEO.CMS.HBG.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byPrereleaseNumber

- task: DotNetCoreCLI@2
  displayName: 'Create packed NuGet files Core'
  inputs:
    command: 'pack'
    packagesToPack: 'src/FEO.CMS.HSB.Core/FEO.CMS.HBG.Core.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byPrereleaseNumber

- task: DotNetCoreCLI@2
  displayName: 'Push packed NuGet files'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishVstsFeed: 'FEO-Optimizely-Platform/FEOR-Optimizely-Integration'
    nuGetFeedType: 'internal'
    
    